name: native_audio_example
description: Demonstrates how to use the native_audio plugin.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.17.0'
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  native_audio:
    path: ../

flutter:
  uses-material-design: true