name: native_audio
description: An audio plugin for Flutter which makes use of the native Android and iOS audio players, handling playback, notifications and external controls.
version: 0.2.7
homepage: https://github.com/gaucidaniel/native-audio

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.danielgauci.native_audio
        pluginClass: NativeAudioPlugin
      ios:
        pluginClass: NativeAudioPlugin